USE [master]
GO

/****** Object:  Database [DDchar]    Script Date: 3/8/2014 2:04:13 PM ******/
CREATE DATABASE [DDchar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DDchar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DDchar.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DDchar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DDchar_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DDchar] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DDchar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DDchar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DDchar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DDchar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DDchar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DDchar] SET ARITHABORT OFF 
GO

ALTER DATABASE [DDchar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DDchar] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DDchar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DDchar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DDchar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DDchar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DDchar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DDchar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DDchar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DDchar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DDchar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DDchar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DDchar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DDchar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DDchar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DDchar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DDchar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DDchar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DDchar] SET RECOVERY FULL 
GO

ALTER DATABASE [DDchar] SET  MULTI_USER 
GO

ALTER DATABASE [DDchar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DDchar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DDchar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DDchar] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DDchar] SET  READ_WRITE 
GO

